use super::NodeHelpPage;

pub fn node_help_page(node_name: &str) -> Option<NodeHelpPage> {
    match node_name {
        "Splat Read" | "Read Splats" => Some(NodeHelpPage {
            name: "Splat Read",
            description: &[
                "Loads Gaussian splats from a PLY file and produces splat primitives.",
                "The reader expects 3DGS-style fields: position, rotation (quaternion), scale (log sigma), opacity (logit), and SH coefficients.",
                "On load, values are validated and normalized so scales and opacity stay in a stable range.",
                "Full SH keeps all bands for relighting and delighting workflows.",
                "Color Only keeps just the DC color/alpha and zeros higher bands for faster loading and lower memory use.",
            ],
            inputs: &[],
            outputs: &["out: Splat geometry."],
            parameters: &[
                ("path", "Path or URL to a splat PLY file."),
                ("read_mode", "Full SH keeps all SH bands; Color Only keeps only DC color/alpha."),
            ],
        }),
        "Splat Write" | "Write Splats" => Some(NodeHelpPage {
            name: "Splat Write",
            description: &[
                "Writes Gaussian splats to a PLY file in a 3DGS-compatible layout.",
                "The node passes geometry through; writing happens only when the Write button is pressed.",
                "On save, splats are normalized so external viewers see stable scales and opacity.",
                "Binary is faster and smaller; ASCII is useful for debugging or interchange.",
            ],
            inputs: &["in: Splat geometry to write."],
            outputs: &["out: Pass-through geometry."],
            parameters: &[
                ("path", "Output PLY file path."),
                ("format", "PLY format: Binary (recommended) or ASCII."),
            ],
        }),
        "Splat Prune" | "Prune" => Some(NodeHelpPage {
            name: "Splat Prune",
            description: &[
                "Filters splats by scale and opacity ranges in splat parameter space.",
                "Scale is stored as log-sigma per axis and opacity is stored as a logit.",
                "Use it to remove tiny, huge, or nearly invisible splats after editing.",
                "Optional invalid removal drops NaNs/Infs for stability.",
            ],
            inputs: &["in: Splat geometry."],
            outputs: &["out: Filtered splats."],
            parameters: &[
                ("min_opacity", "Minimum logit opacity to keep."),
                ("max_opacity", "Maximum logit opacity to keep."),
                ("min_scale", "Minimum log-scale (ln sigma) to keep."),
                ("max_scale", "Maximum log-scale (ln sigma) to keep."),
                ("remove_invalid", "Drop splats with NaN/Inf."),
            ],
        }),
        "Splat Regularize" | "Regularize" => Some(NodeHelpPage {
            name: "Splat Regularize",
            description: &[
                "Clamps splat parameters to a stable range and repairs invalid values.",
                "This reduces numerical drift after heavy edits or deformation.",
                "Normalize rotation re-orthonormalizes the quaternion so orientation stays valid.",
                "It is safe to keep in a pipeline as a stabilization step.",
            ],
            inputs: &["in: Splat geometry."],
            outputs: &["out: Regularized splats."],
            parameters: &[
                ("min_scale", "Minimum log-scale (ln sigma) to keep."),
                ("max_scale", "Maximum log-scale (ln sigma) to keep."),
                ("normalize_opacity", "Renormalize logit opacity to a stable range."),
                ("normalize_rotation", "Normalize/repair rotation quaternions."),
                ("remove_invalid", "Drop splats with NaN/Inf."),
            ],
        }),
        "Splat LOD" => Some(NodeHelpPage {
            name: "Splat LOD",
            description: &[
                "Reduces splat count by clustering splats into a voxel grid.",
                "Each occupied voxel produces one representative splat, preserving the overall shape.",
                "Smaller voxels retain detail; larger voxels are faster and more aggressive.",
                "An optional target count can further cap the output size.",
            ],
            inputs: &["in: Splat geometry."],
            outputs: &["out: Reduced splats."],
            parameters: &[
                ("voxel_size", "Voxel size in world units for clustering."),
                ("target_count", "Optional cap on output splats (0 disables)."),
            ],
        }),
        "Splat to Mesh" => Some(NodeHelpPage {
            name: "Splat to Mesh",
            description: &[
                "Converts splats to either a polygon mesh or an SDF volume.",
                "Density (Iso) voxelizes Gaussian density and extracts a surface with marching cubes.",
                "Ellipsoid (Smooth Min) blends analytic ellipsoids; it can be noisy for meshes but useful for SDFs.",
                "Use Output to choose Mesh or SDF Volume depending on downstream needs.",
            ],
            inputs: &["splats: Splat geometry."],
            outputs: &["out: Mesh or SDF volume."],
            parameters: &[
                ("output", "Output type: Mesh extracts a surface; SDF Volume outputs a signed distance grid."),
                ("algorithm", "Method: Density (Iso) uses a density grid; Ellipsoid (Smooth Min) blends ellipsoids."),
                ("voxel_size", "Base voxel size for the density grid (smaller = higher detail)."),
                ("voxel_size_max", "Maximum grid dimension; voxel size grows to fit this limit."),
                ("n_sigma", "Gaussian support radius in sigmas (larger = thicker, slower)."),
                ("density_iso", "Isovalue for Density (Iso) surface (Density only)."),
                ("surface_iso", "Ellipsoid surface threshold for Smooth Min method (Ellipsoid only)."),
                ("bounds_padding", "Padding around bounds in sigmas."),
                ("transfer_color", "Sample splat color and write to mesh Cd."),
                ("max_m2", "Exponent clamp to avoid overflow in ellipsoid evaluation (Ellipsoid only)."),
                ("smooth_k", "Smooth-min sharpness (higher = sharper union, Ellipsoid only)."),
                ("shell_radius", "Shell thickness for ellipsoid method (Ellipsoid only)."),
                ("blur_iters", "Blur passes on the density grid to smooth surfaces (Density only)."),
            ],
        }),
        "Splat Deform" => Some(NodeHelpPage {
            name: "Splat Deform",
            description: &[
                "Deforms a source splat model using a second input of edited points or splats.",
                "If the second input has matching splat count, positions map by index.",
                "Otherwise, points are consumed in order; extra points can create new splats when enabled.",
                "Derive rotation/scale estimates a local linear transform from neighbors to update orientation.",
            ],
            inputs: &["source: Original splats.", "deform: Edited point cloud or splats."],
            outputs: &["out: Deformed splats."],
            parameters: &[
                ("allow_new", "Allow new splats when target has more points; attributes are copied from nearest sources."),
                ("derive_rot_scale", "Infer rotation/scale from local deformation; disable to move centers only."),
            ],
        }),
        "Splat Delight" => Some(NodeHelpPage {
            name: "Splat Delight",
            description: &[
                "Removes baked lighting from splat SH coefficients to approximate albedo-like splats.",
                "Band 0 Only flattens to DC when you want a quick neutralization.",
                "SH Ratio divides each SH band by an estimated environment, preserving higher-frequency detail.",
                "Irradiance Divide estimates diffuse irradiance from SH and normals, then solves for per-splat albedo.",
                "Env Splat uses the second input as the environment (for delighting a cut-out from a larger scan).",
                "Uniform modes apply a constant environment; Custom uses the provided color.",
            ],
            inputs: &[
                "in: Splat geometry.",
                "env: Optional environment splats for Env Splat mode.",
            ],
            outputs: &["out: Delit splats."],
            parameters: &[
                ("delight_mode", "Mode: Band 0 Only, SH Ratio, Irradiance Divide, or Env Splat."),
                ("source_env", "Lighting source: From Splats, Uniform White, or Custom."),
                ("neutral_env", "Neutral target: Uniform White or Custom."),
                ("source_color", "Custom source lighting color (DC) when Source Env is Custom."),
                ("neutral_color", "Custom neutral color (DC) when Neutral Env is Custom."),
                ("eps", "Stability epsilon to avoid divide-by-zero."),
                ("ratio_min", "Minimum ratio clamp for SH Ratio mode."),
                ("ratio_max", "Maximum ratio clamp for SH Ratio mode."),
                ("high_band_gain", "Gain applied to higher SH bands."),
                ("output_sh_order", "Output SH order: L0, L1, L2, or L3."),
                ("albedo_max", "Maximum albedo clamp for Irradiance Divide."),
                ("group", "Optional group to restrict delighting."),
                ("group_type", "Group domain to use."),
            ],
        }),
        "Splat Integrate" => Some(NodeHelpPage {
            name: "Splat Integrate",
            description: &[
                "Relights splats to match a target environment or a target splat set.",
                "From Splats modes use opacity-weighted averages; Uniform White gives neutral lighting.",
                "SH Ratio scales all SH bands to match the target environment.",
                "Diffuse replaces lighting using irradiance only (albedo-like relighting).",
                "Hybrid relights DC via irradiance and preserves or scales higher bands.",
                "Use the target splat input to transfer lighting from another scan.",
            ],
            inputs: &[
                "source: Splat geometry to relight.",
                "target: Optional target splats for lighting.",
            ],
            outputs: &["out: Relit splats."],
            parameters: &[
                ("relight_mode", "Mode: SH Ratio, Diffuse, or Hybrid."),
                ("source_env", "Source lighting: From Splats, Uniform White, or Custom."),
                ("target_env", "Target lighting: From Splats, Uniform White, or Custom."),
                ("source_color", "Custom source lighting color (DC) when Source Env is Custom."),
                ("target_color", "Custom target lighting color (DC) when Target Env is Custom."),
                ("eps", "Stability epsilon to avoid divide-by-zero."),
                ("ratio_min", "Minimum ratio clamp for SH Ratio mode."),
                ("ratio_max", "Maximum ratio clamp for SH Ratio mode."),
                ("high_band_gain", "Gain applied to higher SH bands."),
                ("high_band_mode", "High-band mode: Scale Only or Scale + Ratio."),
                ("output_sh_order", "Output SH order: L0, L1, L2, or L3."),
                ("albedo_max", "Maximum albedo clamp for Diffuse/Hybrid relighting."),
                ("group", "Optional group to restrict integration."),
                ("group_type", "Group domain to use."),
            ],
        }),
        "Splat Heal" => Some(NodeHelpPage {
            name: "Splat Heal",
            description: &[
                "Fills holes in splat surfaces by generating new splats in under-dense regions.",
                "Voxel Close builds a density grid, performs morphological closing, then resplats missing surface voxels.",
                "SDF Patch evaluates an ellipsoid SDF band and places splats near the implied surface while skipping occupied voxels.",
                "Use Heal Bounds to limit work to a box or sphere; Preview Surface can output a debug mesh of the healed surface.",
            ],
            inputs: &["in: Splat geometry."],
            outputs: &["out: Healed splats (original + new)."],
            parameters: &[
                ("group", "Optional group to restrict healing."),
                ("group_type", "Group domain to use."),
                ("heal_shape", "Heal bounds: All, Box, or Sphere."),
                ("method", "Method: Voxel Close or SDF Patch."),
                ("voxel_size", "Voxel size for the density grid (smaller = more detail)."),
                ("voxel_size_max", "Maximum voxel dimension (safety clamp)."),
                ("n_sigma", "Gaussian support radius in sigmas."),
                ("density_iso", "Density threshold for occupancy."),
                ("bounds_padding", "Padding around bounds in sigmas."),
                ("close_radius", "Closing radius in voxels (Voxel Close only)."),
                ("fill_stride", "Subsample candidates (higher = fewer splats)."),
                ("max_new", "Maximum number of new splats."),
                ("sdf_band", "SDF band thickness around the surface (SDF Patch only)."),
                ("sdf_close", "SDF offset to close small gaps (SDF Patch only)."),
                ("search_radius", "Neighbor search radius for copying attributes (auto if <= 0)."),
                ("min_distance", "Minimum distance to existing splats (auto if <= 0)."),
                ("scale_mul", "Scale multiplier for new splats."),
                ("opacity_mul", "Opacity multiplier for new splats."),
                ("copy_sh", "Copy full SH coefficients (else DC only)."),
                ("preview_surface", "Preview the healed surface as a mesh."),
                ("max_m2", "Exponent clamp for SDF method (SDF Patch only)."),
                ("smooth_k", "Smooth-min blend sharpness (SDF Patch only)."),
                ("shell_radius", "Ellipsoid shell radius (SDF Patch only)."),
                ("blur_iters", "Density blur iterations (Voxel Close only)."),
            ],
        }),
        "Splat Outlier" => Some(NodeHelpPage {
            name: "Splat Outlier",
            description: &[
                "Removes stray splats by clustering in position space and discarding noise.",
                "The node runs a DBSCAN-style density pass and deletes splats that do not have enough neighbors.",
                "Use min_cluster_size to remove tiny clusters that float away from the main surface.",
                "Tweak eps and min_pts to control how aggressively it cleans sparse regions.",
            ],
            inputs: &["in: Splat geometry."],
            outputs: &["out: Splats with outliers removed."],
            parameters: &[
                ("group", "Optional group to restrict outlier removal."),
                ("group_type", "Group domain to use."),
                ("eps", "Neighborhood radius for clustering (<= 0 uses auto spacing)."),
                ("min_pts", "Minimum neighbors for a core splat."),
                ("min_cluster_size", "Remove clusters smaller than this size (0 disables)."),
            ],
        }),
        "Splat Cluster" => Some(NodeHelpPage {
            name: "Splat Cluster",
            description: &[
                "Assigns a cluster id to each splat for selection and downstream editing.",
                "Grid mode bins splats into spatial cells for fast, deterministic clustering.",
                "DBSCAN mode groups splats by local density and labels noise as -1.",
                "The cluster id is stored in the chosen attribute as an integer.",
            ],
            inputs: &["in: Splat geometry."],
            outputs: &["out: Splats with a cluster attribute."],
            parameters: &[
                ("group", "Optional group to restrict clustering."),
                ("group_type", "Group domain to use."),
                ("method", "Clustering method: Grid (fast) or DBSCAN (density-based)."),
                ("attr", "Attribute name to store the cluster id (integer)."),
                ("cell_size", "Grid cell size (<= 0 uses auto spacing)."),
                ("eps", "DBSCAN radius (<= 0 uses auto spacing)."),
                ("min_pts", "Minimum neighbors for a DBSCAN core."),
            ],
        }),
        "Splat Merge" => Some(NodeHelpPage {
            name: "Splat Merge",
            description: &[
                "Geometrically joins two splat models by softening their seam.",
                "Feather fades overlapping splats based on distance and blends the two inputs.",
                "Skirt generates new bridging splats between nearby pairs to fill gaps at the seam.",
                "Use seam parameters to control opacity, scale, and whether to use DC-only SH.",
            ],
            inputs: &["a: First splat model.", "b: Second splat model."],
            outputs: &["out: Merged splats."],
            parameters: &[
                ("method", "Join method: Feather or Skirt."),
                ("blend_radius", "Blend radius for feathering/fade (Feather mode)."),
                ("fade_originals", "Fade original splats near the seam."),
                ("skirt_max_dist", "Maximum distance to bridge with skirt splats (Skirt mode)."),
                ("skirt_step", "Spacing between skirt splats (Skirt mode)."),
                ("skirt_max_new", "Maximum skirt splats per pair (Skirt mode)."),
                ("seam_alpha", "Opacity for seam splats."),
                ("seam_scale", "Scale multiplier for seam splats."),
                ("seam_dc_only", "Use DC-only SH for seam splats."),
                ("preview_skirt", "Preview skirt geometry as wireframe when selected."),
            ],
        }),
        _ => None,
    }
}
